import scpm

env = Environment(tools=[scpm.setup], BUILDROOT="#scons_build/$BOARD",
                  BOARD=ARGUMENTS.get("board", "native"))

ypp = env.Load("ypp", "../..")
ypp_board_stm32 = env.Load("ypp_board_stm32", "../../../ypp_board_stm32")

program = env.YPPMainProgram(
    "$BUILDROOT/main.elf", ["$BUILDROOT/main.cpp"] + env.UniqueFlatten(ypp_board_stm32 + ypp))
