import os
import scpm

env = Environment(tools=[scpm.setup],
                  BUILDROOT="#scons_build/$BOARD",
                  BOARD=os.environ.get("BOARD", "native"))

ypp = env.Load("ypp", "../..")
ypp_board_stm32 = env.Load("ypp_board_stm32", "../../../ypp_board_stm32")

program = env.YPPMainProgram(
    "$BUILDROOT/hello_world", ["$BUILDROOT/hello_world.cpp"] + env.UniqueFlatten(ypp_board_stm32 + ypp))
