import scpm

env = Environment(tools=[scpm.setup], CPPFLAGS="-std=c++17")

ypp = env.Load("ypp", "../..")

program = env.MainProgram("$BUILDROOT/hello_world",
                          ["$BUILDROOT/hello_world.cpp", ypp])
