cc_library(
    name = "kernel",
    srcs = ["scheduler.cpp"],
    hdrs = [
        "bit_priority_queue.h",
        "circ_queue.h",
        "scheduler.h",
        "task.h",
    ],
    visibility = ["//visibility:public"],
)
